
services:
  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: todomaster-frontend-local:latest
    container_name: todo-frontend
    environment:
      REACT_APP_API_URL: /api
    ports:
      - "80:80"
    networks:
      - todo-network
    restart: unless-stopped

networks:
  todo-network:
    external: true
    name: backend_todo-network